<h1>Linear regression with PyTorch</h1>



![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)



<h2>Installations</h2>

In [4]:
!pip install torch numpy --quiet

In [5]:
import torch 
import numpy as np

<h2>Training Data</h2>

<h3>Inputs: Temperature, Rainfall, Humidity</h3>

In [8]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype="float32")

<h3>Targets: Apples, Oranges</h3>

In [10]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype="float32")

<h3>Numpy to Tensors</h3>

In [12]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


<h3>Weights and Biases</h3>

In [14]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.4073, -0.6429,  0.2254],
        [-0.8162, -2.1715,  1.3886]], requires_grad=True)
tensor([-1.0690,  0.3698], requires_grad=True)


In [15]:
def model(x):
    return x @ w.t() + b

<h3>Predictions</h3>

In [17]:
preds = model(inputs)
print(preds)

tensor([[  -4.7138, -144.9880],
        [  -6.1488, -176.1189],
        [ -38.7023, -281.0743],
        [  21.1757, -124.8724],
        [ -18.9010, -167.2037]], grad_fn=<AddBackward0>)


In [18]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


<h2>Loss Functions</h2>

<h3>MSE Loss</h3>

In [21]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff*diff) / diff.numel()

In [22]:
losses = mse(preds, targets)
losses

tensor(45359.9180, grad_fn=<DivBackward0>)

<h2>Adjust Weights and Biases using Gradient Decent</h2>

In [24]:
pred = model(inputs)
preds

tensor([[  -4.7138, -144.9880],
        [  -6.1488, -176.1189],
        [ -38.7023, -281.0743],
        [  21.1757, -124.8724],
        [ -18.9010, -167.2037]], grad_fn=<AddBackward0>)

In [25]:
loss =  mse(preds, targets)
loss

tensor(45359.9180, grad_fn=<DivBackward0>)

In [26]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -6915.6006,  -8921.3955,  -5179.7046],
        [-22639.0898, -25742.5371, -15403.9883]])
tensor([ -85.6581, -270.8515])


In [27]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [28]:
print(w)
print(b)

tensor([[ 0.4765, -0.5537,  0.2772],
        [-0.5898, -1.9141,  1.5427]], requires_grad=True)
tensor([-1.0682,  0.3725], requires_grad=True)


In [29]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(31093.0742, grad_fn=<DivBackward0>)

<h2>Train for multiple epoch</h2>

In [95]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5

In [97]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(2778.5889, grad_fn=<DivBackward0>)

In [99]:
preds

tensor([[57.5721, 47.1016],
        [76.7655, 51.4631],
        [56.6878, 58.4032],
        [82.4344, 76.0682],
        [61.7776, 27.0117]], grad_fn=<AddBackward0>)

In [63]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])