<h1>Pytorch Basics</h1>

<h2>Installations</h2>

In [3]:
# !pip install torch numpy --quiet

In [4]:
import torch

<h2>Tensors</h2>

In [6]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [7]:
t1.dtype

torch.float32

<h3>Matrix</h3>

In [9]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

<h3>Vector</h3>

In [11]:
t3 = torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

<h3>3 Dimensional Array</h3> 

In [13]:
t4 = torch.tensor([
    [[11.,12,13],
     [13,14,15]],
    [[15,16,17],
     [17,18,19]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

<h3>Dimensions</h3>

In [15]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [16]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [17]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [18]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

<h2>Tensor Operation and gradients</h2>

In [20]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [21]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [22]:
y.backward

<bound method Tensor.backward of tensor(17., grad_fn=<AddBackward0>)>

In [23]:
print("dy/dx:", x.grad)
print("dy/dw:", w.grad)
print("dy/db:", b.grad)

dy/dx: None
dy/dw: None
dy/db: None


<h2>Interoperability with numpy</h2>

In [25]:
import numpy as np

In [26]:
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [27]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [28]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [29]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])